openapi: "3.0.2"
info:
  title: LMS connect
  version: "1.0.0"
servers:
  - url: https://cursuskit.test/lms-connect/api/v1
paths:
  /health:
    get:
      summary: Get the health of the connect plugin
      description: This endpoint should return status 'ok' when installed.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /{team}/groups:
    get:
      summary: Get all groups for a given team
      description: You can get all the groups for a given team.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      users_count:
                        type: integer
                        description: Counts the users in the group
                      team_id:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
  /{team}/groups/scores:
    get:
      summary: Get all the groups with their score for a given team
      description: It returns all the scores for the groups in a team.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      users_count:
                        type: integer
                        description: Counts the users in the group
                      users_started:
                        type: integer
                        description: Counts the users who started a course in the group
                      users_achieved:
                        type: integer
                        description: Counts the users who completed courses in the group
  /{team}/users:
    get:
      summary: Get all the users for a given team
      description: It returns all the users in a team.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string

  /{team}/groups/{group}/scores:
    get:
      summary: Get all scores of users for a given group in a team
      description: It returns a list with scores.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: string
                        phone:
                          type: string
                        lms_roles:
                          type: string
                        last_seen_at:
                          type: string
                        created_at:
                          type: string
                        score:
                          type: integer
                        courses:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                              achieved:
                                type: boolean
                              score:
                                type: integer
